/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.4 and the DSP System Toolbox 8.7.
 * Generated on: 28-Apr-2021 18:42:25
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 8
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 * Arithmetic        : single
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2014b\extern\include\tmwtypes.h 
 */
#define N  2
/*const float B[8] = {
   0.002231751801, -0.03200045601,  0.04181296006,    0.487955749,    0.487955749,
    0.04181296006, -0.03200045601, 0.002231751801
};*/
const float B[] = {0.5 , 0.5};
