/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.4 and the Signal Processing Toolbox 6.22.
 * Generated on: 13-May-2021 15:02:58
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 16
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2014b\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
//const int BL = 16;
const float Bderiv[16] = {
   0.008417107165,  0.01319226995,  0.02658254839,  0.04701336101,   0.0712562874,
    0.09505324066,    0.113999337,   0.1244858503,   0.1244858503,    0.113999337,
    0.09505324066,   0.0712562874,  0.04701336101,  0.02658254839,  0.01319226995,
   0.008417107165
};


