/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.4 and the Signal Processing Toolbox 6.22.
 * Generated on: 03-May-2021 18:29:21
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 16
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2014b\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int BL = 16;
const float B[16] = {
   0.009767927229,  0.01462908927,   0.0283708144,  0.04862345383,  0.07188764215,
     0.0941401422,   0.1115308627,   0.1210500672,   0.1210500672,   0.1115308627,
     0.0941401422,  0.07188764215,  0.04862345383,   0.0283708144,  0.01462908927,
   0.009767927229
};
