/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.4 and the DSP System Toolbox 8.7.
 * Generated on: 28-Apr-2021 22:39:08
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 101
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 * Arithmetic        : single
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2014b\extern\include\tmwtypes.h 
 */
const int N = 8;
const float B[] = {
		1/8.0, 1/8.0, 1/8.0, 1/8.0, 1/8.0, 1/8.0, 1/8.0, 1/8.0
};
