/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.4 and the DSP System Toolbox 8.7.
 * Generated on: 28-Apr-2021 20:31:00
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 8
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 * Arithmetic        : single
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2014b\extern\include\tmwtypes.h 
 */
const int N = 8;
const float B[8] = {
    0.03124982491,  0.09374980628,   0.1562500447,   0.2187503278,   0.2187503278,
     0.1562500447,  0.09374980628,  0.03124982491
};
